version: '3.8'

services:
  nginx:
    image: nginx:latest

    container_name: nginx

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/app
    
    ports:
      - '8000:80'

    depends_on:
      - app

  app:
    build:
      context: src
      dockerfile: Dockerfile

    container_name: app

    volumes:
      - ./src:/var/www/app

    depends_on:
      - database

  database:
    image: mysql:latest

    container_name: database

    environment:
      - MYSQL_DATABASE=AceTheInterview
      - MYSQL_ROOT_PASSWORD=1234

    volumes:
      - ./dbdata:/var/lib/myslq
